const data = {
    products: [
        {
            _id: '1',
            name: 'Sweat Corn',
            category: 'Vegetables',
            image: '/images/sweetcorn.jpg',
            price: 3,
            brand: 'Solomon Island',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality fresh vegetable',

        },
        {
            _id: '2',
            name: 'Coconut',
            category: 'Fruits',
            image: '/images/coconut.jpg',
            price: 5,
            brand: 'Solomon Island',
            rating: 5.0,
            numReviews: 16,
            description: 'high quality fresh fruit',
        },
        {
            _id: '3',
            name: 'Tomato',
            category: 'Vegetables',
            image: '/images/tomato.jpg',
            price: 2,
            brand: 'Solomon Island',
            rating: 4.8,
            numReviews: 7,
            description: 'high quality fresh vegetable',
        },

        {
            _id: '4',
            name: 'Avocado',
            category: 'Vegetables',
            image: '/images/avocado.jpg',
            price: 2.5,
            brand: 'Solomon Island',
            rating: 4.4,
            numReviews: 12,
            description: 'high quality fresh vegetable',
        },
        {
            _id: '5',
            name: 'Peach',
            category: 'Fruites',
            image: '/images/peach.jpg',
            price: 4,
            brand: 'Solomon Island',
            rating: 4.7,
            numReviews: 20,
            description: 'high quality fresh fruit',
        },

        {
            _id: '6',
            name: 'Cucumber',
            category: 'Vegetables',
            image: '/images/cucumber.jpg',
            price: 1.2,
            brand: 'Solomon Island',
            rating: 4.6,
            numReviews: 19,
            description: 'high quality fresh vegetable',
        },
        {
            _id: '7',
            name: 'Cabbage',
            category: 'Vegetables',
            image: '/images/cabbage.jpg',
            price: 3,
            brand: 'Solomon Island',
            rating: 4.2,
            numReviews: 6,
            description: 'high quality fresh vegetable',
        },
        {
            _id: '8',
            name: 'Orange',
            category: 'Fruits',
            image: '/images/orange.jpg',
            price: 3.5,
            brand: 'Solomon Island',
            rating: 5.0,
            numReviews: 23,
            description: 'high quality fresh fruit',
        },
    ],
};

export default data;